root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "./build.sh" 
  delay = 1000
  exclude_dir = [
      "assets"          ,
      "tmp"             ,
      "vendor"          ,
      "testdata"        ,
      "open-webui-data" ,
      "postgres-data"   ,
      "mongo-data"      ,
      "whisper-data"    ,
      "qdrant-data"     ,
      "ollama-data"     , 
      "redis-data"      ,
      "data"            , 
    ]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = [
      "sh"              ,
      "go"              ,
      "tpl"             ,
      "tmpl"            ,
      "html"            ,
      "env"             ,
      ".air.toml"       ,
      "toml"            ,
  ]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false 
  poll_interval = 0
  post_cmd = []
  pr_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
